### PR TITLE
Split the build.

### PR DESCRIPTION
**Pull request by jonathanpallant**
Now the examples has a job, and building the examples in Ferrocene has a job.

This means third-parties who submit PRs can still pass most of the tests.

### CODE REVIEW

**Comment by jonathanpallant** [comment]
Rebased

**Comment by miguelraz** [comment]
I'm happy to see that all but the `build` job finished in under a minute.

**Review by miguelraz — APPROVED** [review]

**Comment by jonathanpallant** [comment]
I don't see anything hanging?

**Comment by jonathanpallant** [comment]
ah, the branch rule is waiting for a job that no longer exists. Ugh, GHA is so annoying.

**Pull request merged**
