### PR TITLE
Use the same template as material-templates

### PR DESCRIPTION
**Pull request by jonathanpallant**
Taken from https://github.com/ferrous-systems/material-templates/pull/16/commits/8f67dfdb481a821780cc34e9a9d9fbc66e63057c

Wait for https://github.com/ferrous-systems/material-templates/pull/16 to go through first.

### CODE REVIEW

**Comment by Mirabellensaft** [comment]
What do I need to look at here exactly?

**Comment by jonathanpallant** [comment]
Just check the artefacts look OK, and that I correctly copied the `template.html` file from the `material-templates` repo.

**Review by Mirabellensaft — COMMENTED** [review]
artefacts look ok, but I think the template.html file in the material-templates has changed in the mean time

**Comment by jonathanpallant** [comment]
Ah, yes. Let's get https://github.com/ferrous-systems/material-templates/pull/16 merged and then we can pick up the `code` background changes too.

**Review by Mirabellensaft — APPROVED** [review]

**Pull request merged**
